[debian]
192.168.199.131 ansible_user=labuser ansible_port=2222
192.168.199.133 ansible_user=labuser
[rocky]
192.168.199.132 ansible_user=admin ansible_port=2222

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=~/.ssh/id_ansible
